version: '3'

services:
  details:
    container_name: details
    build: .
    command: bash -c "npm run seed && npm run start"
    depends_on:
      - "database"
    ports:
      - "3001:3001"
  database:
    container_name: database
    image: mongo:latest
    ports:
      - "27017:27017"
