version: '3'

services:
  details:
    image: bcronin2/fec-airbnh-details:ssr
    command: bash -c "npm run seed && npm run start"
    depends_on:
      - "database"
    ports:
      - "80:3001"
  database:
    container_name: database
    image: mongo:latest
    ports:
      - "27017:27017"