version: 2
jobs:
  build:
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:10-browsers
      - image: circleci/mongo:4
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Seed database
          command: npm run seed
      - run:
          name: Test
          command: npm test
